### ISSUE TITLE
Upgrade cosmos-sdk v0.50 get error "no concrete type registered for type URL /cosmwasm/wasm/v1beta1/UpdateAdminProposal"

### ISSUE THREAD

**Issue by ledinhhuy1811** [oraichain/wasmd#16]
## Context
Before we run upgrade to cosmos-sdk v0.50 in our mainnet, we fork current mainnet to a testnet with fully data of our mainnet. The purpose of this is that we want to upgrade in our fork-mainnet (testnet) first to see if we got error.

We run e2e-upgrade script first to check if there is error or not and it work without errors but when we try to upgrade to cosmos-sdk v0.50 in our testnet, the error is show up:

![image](https://github.com/user-attachments/assets/dd7086b5-5fab-4f0c-8d00-69fd299e1125)

## To Reproduce
1. Need to fork mainnet and run node
2. Clone our [old repo](https://github.com/oraichain/orai) and build oraid binary
3. Try to make proposal to upgrade fork-mainnet
4. Clone this repo and checkout to [this commit](https://github.com/oraichain/wasmd/commit/3259ea69bcdf246af16682ec04f9dd5fe09b527c)
5. Build new binary and re run node to see error

## Expected behavior
The upgrade process pass and node start to commit block.

**Comment by ledinhhuy1811** [comment]
The error show up because our old orai version we support `wasm v1bete1` but in new cosmos-sdk v0.50 version, wasm support `v1` not `v1beta1`. Then when we try to run upgrade, the error will show up.

**Comment by ledinhhuy1811** [comment]
To fix this error, we try to add logic support `wasm/v1beta1` and it work. 

Fixed in [here](https://github.com/oraichain/wasmd/tree/fix/backward-compatible-cw-proposals)

**Comment by ducphamle2** [comment]
New commit after merging: fe53dbfccd81b69846ac6ba71f9bc6aaf0d78b62
