### ISSUE TITLE
Orai build error on a fresh profile

### ISSUE THREAD

**Issue by m8nky** [oraichain/wasmd#26]
## Context
Try to build oraid on a fresh go env, results in a build error in final step.

## To Reproduce

1. Upgrade go to 1.22
2. Delete ~/go
3. Follow 0.50.0 upgrade guide:
  ```bash
git clone https://github.com/oraichain/wasmd
cd wasmd
git checkout v0.50.0
# NOTE: you may need to upgrade your Golang version to 1.22.6+ with GOTOOLCHAIN to build the binary
make build
```

```
mv: cannot move 'build/oraid' to '/var/lib/orai/go/bin/oraid': No such file or directory
make: *** [Makefile:86: build] Error 1
```

## Expected behavior
No build error

## Additional context
https://github.com/oraichain/wasmd/blob/a71fabc622f20aa4a13f3995e24ffdf70bfc6c5c/Makefile#L86

Maybe like this:
```
go build -mod=readonly $(BUILD_FLAGS) -o build/oraid ./cmd/wasmd && mkdir -p $(GOPATH)/bin && mv build/oraid $(GOPATH)/bin/oraid
```

**Comment by ducphamle2** [comment]
Thanks for reporting. Nice catch! Let us fix it and have It updated in the next release
