### ISSUE TITLE
Failed to prune store err=Value missing for key

### ISSUE THREAD

**Issue by ducphamle2** [oraichain/wasmd#27]
## Context

When starting a node with prune mode=default or mode=everything -> the node will show pruning errors like in the title. This bug is from the new IAVL 1.2.0 version and is patched in the release 1.2.x branch.

## To Reproduce

1. Set the prune mode=default or mode=everything.
2. Start an Oraichain node version 0.50.
3. Observe the logs and seek this error: `Failed to prune store... or Error deleting legacy versions`

## Expected behavior

There shouldn't be any error logs

## Screenshots

![image](https://github.com/user-attachments/assets/8fe03587-2a9e-42e5-8d99-6901cbd5927a)
![image](https://github.com/user-attachments/assets/788c8a97-62ad-4265-aea9-aeb64bc13cba)

## Additional context

The bug is originally mentioned here: https://github.com/crypto-org-chain/cronos/issues/1672

How they resolved: https://github.com/crypto-org-chain/cronos/pull/1673

**Comment by yihuang** [comment]
> How they resolved

not resolved actually, the sdk team is still working on it.

**Comment by ducphamle2** [comment]
> > How they resolved
> 
> not resolved actually, the sdk team is still working on it.

really? thats sad. Does it work with custom pruning? Or it has to be prune=nothing

**Comment by ducphamle2** [comment]
Current workaround: Use prune=nothing

**Comment by ducphamle2** [comment]
@yihuang you have any news regarding this bug? Does this PR fix the issue? https://github.com/crypto-org-chain/cronos/pull/1702

**Comment by yihuang** [comment]
> @yihuang you have any news regarding this bug? Does this PR fix the issue? https://github.com/crypto-org-chain/cronos/pull/1702

iavl 1.2.2 should have fixed that

**Comment by ducphamle2** [comment]
@yihuang that's good news. Thanks for your info, let us patch it!
