### ISSUE TITLE
Simulation: Simulation not running

### ISSUE THREAD

**Issue by GNaD13** [oraichain/wasmd#37]
## Context
Current simulation feature not running.

## To Reproduce
run `make test-sim-multi-seed-short`

**Comment by ducphamle2** [comment]
Im quite curious about the Cosmos SDK's simulation feature (I have never used it before). What's the difference between it versus interchaintest versus existing integration testing (mocking and stuff) of Cosmos SDK?

**Comment by GNaD13** [comment]
> Im quite curious about the Cosmos SDK's simulation feature (I have never used it before). What's the difference between it versus interchaintest versus existing integration testing (mocking and stuff) of Cosmos SDK?

Interchaintest is very useful for us to testing the feature that may relevant with lots of things in the realistic environment (running all the things in docker) instead of mocking test. Unlike Interchaintest, simulation is useful for stress test. It allow us to define all the input parameter of all msg or proposals that we write. With this stress test, we can confirm that all the logic we write will be working fine when the data input is valid. About the integration testing, this is a very detail testing, we could use this test to ensure that every logic that we write is working correctly in detail (every single func), and it would be very useful when we update dependency.

**Comment by GNaD13** [comment]
Fixed via #51
